# Generated by Django 6.0.3 on 2026-03-31 07:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Curs')),
                ('name', models.CharField(max_length=255, verbose_name='Nume Curs')),
                ('date_start', models.DateField(verbose_name='Data Inceput')),
                ('date_end', models.DateField(verbose_name='Data Final')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Rating')),
                ('number_credits', models.PositiveIntegerField(default=0, verbose_name='Nr. Credite')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Eveniment')),
                ('name', models.CharField(max_length=255, verbose_name='Nume Eveniment')),
                ('event_date', models.DateTimeField(verbose_name='Data Evenimentului')),
                ('location', models.CharField(max_length=255, verbose_name='Locație')),
                ('emc_points', models.PositiveIntegerField(default=0, verbose_name='Puncte EMC')),
                ('delivery_mode', models.CharField(choices=[('physical', 'Fizic'), ('online', 'Online'), ('hybrid', 'Hibrid')], default='online', max_length=10, verbose_name='Cum se desfasoara evenimentul')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('magazine_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Revistă')),
                ('title', models.CharField(max_length=255, verbose_name='Titlu Revistă')),
                ('category', models.CharField(max_length=100, verbose_name='Categorie')),
                ('edition_number', models.PositiveIntegerField(verbose_name='Număr Ediție')),
                ('edition_year', models.PositiveIntegerField(verbose_name='An Ediție')),
                ('publication_date', models.DateField(verbose_name='Data Publicării')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cnp', models.CharField(max_length=13, unique=True, verbose_name='CNP')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('correspondence_address', models.TextField(verbose_name='Adresa de Corespondenta')),
                ('county', models.CharField(max_length=100, verbose_name='Judet')),
                ('city', models.CharField(max_length=100, verbose_name='Localitate')),
                ('user_type', models.CharField(max_length=50, verbose_name='Tip User')),
                ('occupation', models.CharField(max_length=100, verbose_name='Ocupatie')),
                ('specialization_1', models.CharField(max_length=150, verbose_name='Specializare')),
                ('specialization_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Specializare 2')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sectia')),
                ('is_snmf_member', models.BooleanField(default=False, verbose_name='Membru SNMF')),
                ('minors_count', models.PositiveIntegerField(default=0, verbose_name='Nr minori')),
                ('cmv', models.CharField(blank=True, max_length=100, null=True, verbose_name='CMV')),
                ('stamp_code', models.CharField(max_length=50, verbose_name='Cod parafa')),
                ('cuim', models.CharField(max_length=50, verbose_name='CUIM')),
                ('academic_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titlu universitar')),
                ('institution_name', models.CharField(max_length=200, verbose_name='Denumirea institutiei')),
                ('institution_address', models.TextField(blank=True, null=True, verbose_name='Adresa institutiei')),
                ('institution_county', models.CharField(blank=True, max_length=100, null=True, verbose_name='Judet institutie')),
                ('institution_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localitate institutie')),
                ('consent_email', models.BooleanField(default=True, verbose_name='Acord email')),
                ('consent_sms', models.BooleanField(default=False, verbose_name='Acord SMS')),
                ('consent_postal', models.BooleanField(default=False, verbose_name='Acord posta')),
                ('status', models.CharField(default='Activ', max_length=50, verbose_name='Status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Certificat')),
                ('name', models.CharField(max_length=255, verbose_name='Nume Curs Certificat')),
                ('issue_date', models.DateField(verbose_name='Data Eliberării')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course', verbose_name='Curs sursa')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, verbose_name='Categorie')),
                ('product_name', models.CharField(max_length=255, verbose_name='Produs/Serviciu')),
                ('transaction_reference', models.CharField(max_length=100, unique=True, verbose_name='Cod Tranzactie')),
                ('status', models.CharField(choices=[('completed', 'Finalizat'), ('pending', 'In asteptare'), ('failed', 'Esuat')], default='pending', max_length=20, verbose_name='Status')),
                ('date', models.DateTimeField(verbose_name='Data Tranzactiei')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Metoda de plata')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sumă Platita')),
                ('currency', models.CharField(default='RON', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='Progres (%)')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted_date', models.DateTimeField(auto_now_add=True)),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.magazine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
