# Generated by Django 6.0.3 on 2026-04-13 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='usermagazine',
            unique_together={('user', 'magazine')},
        ),
        migrations.CreateModel(
            name='ManualCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titlu Activitate')),
                ('score', models.PositiveIntegerField(verbose_name='Puncte EMC')),
                ('year', models.PositiveIntegerField(verbose_name='An')),
                ('credit_type', models.CharField(default='external', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
